version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-ecommerce
    ports:
      - "9110:9000"
      - "9002:9001"
    volumes:
      - ./docs:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"